### PR TITLE
updating items

### PR DESCRIPTION
**Pull request by jdschmi1**

### CODE REVIEW

**Comment by corroded** [comment]
WOw thanks for this! Was tryign to find time myself to ad the 7*s lol. One problem though, it seems github can't automatically merge the PR because there are some conflicts. Looks like because you also added turbo + bulbs which I already added before? If you know how to rebase, please do so. Otherwise, let me know so I can help you out with it!

I'll try to rebase this either today or tomorrow if you can't by then :) Thanks so much!

**Comment by jdschmi1** [comment]
No prob. My regular PC is not working so I can't upload too much and/or solve these issues as I'm using the web interface. Feel free to copy the code back over to your repo. I was going to try working on exporting/importing files as well

**Comment by corroded** [comment]
Hey @jdschmi1 sorry it's been a while. I'll try to get on merging this soon. I haven't had much time lately but will try to do so. Thanks again!

**Comment by jdschmi1** [comment]
I know the feeling. I might have a bit of time this weekend, but not sure if I will be around a PC. I want to try and get a working database of owned units as well (sorta tied in with this). Right now I just spreadsheet it

**Comment by jdschmi1** [comment]
Just updated application.js with all of the new global 7*s. Still need to
grab the pictures for MechaGods

**Comment by jdschmi1** [comment]
Since my latest checkin I'm not seeing any merge issues on my branch. Want to check to see if you are still seeing them?

**Comment by corroded** [comment]
@jdschmi1 hey sorry been busy. Yup still getting it here. Really sorry haven't been able to check. I'll try tonight or tomorrow at work. I think there re conflicts because I already have some of the stuff you added after you forked the branch. If possible I think you can easily do this by fixing the conflicts through rebasing to branch.

**Comment by jdschmi1** [comment]
No prob. I downloaded the GitHub app for Windows and think I have
everything appropriately synced up now

**Comment by corroded** [comment]
Hmmm im still seeing a can't merge message. Are you sure you got all my new commits from before? and did you push your changes?

**Comment by jdschmi1** [comment]
I committed them but don't think I pushed them. I'm pretty new to git
(usually use svn). Maybe I'll just restart from scratch

**Comment by corroded** [comment]
@jdschmi1  i finally managed to merge this. I took out a stray "load" button and fixed some stuff. There are still stuff missing like tones but i'll be working on those. thanks for all the help! again, really sorry for the delays!

pro-tip: looking at the conflicts, it looks like you are using a very old branch as a base. Best thing to do is to probably just fork or pull my newest changes again.

**Comment by jdschmi1** [comment]
Once I get home tonight I will re-pull all of your newest stuff and
continue working from there. Thanks for getting the branch fixed

**Comment by corroded** [comment]
no worries. what are you planning to add btw? I have already added tones and am working on adding mech gods to the list

**Comment by jdschmi1** [comment]
In my latest app.js file I had already added the mech gods and legend
stone. I hadn't added them to the table though. I was going to work on
saving and loading a file

**Comment by corroded** [comment]
Yeah I already merged that (the fix you made with mech gods and legend stones) you can view your stuff at http://corroded.github.io/eevee now. 

I was also fixing the mech gods and legend stones into the table. just need to parse them properly since they're two words unlike the other evo mats that only have 1 word.

**Comment by corroded** [comment]
By the way, since this has been merged, it would be easier for you to just delete/rename your gh-pages branch and fetch the newest one since it already contains the merged changes from you.

Let me know if you need any help in this, but Github has the necessary guide for this. Thanks!

**Pull request merged**
